'use client'

import * as React from 'react'
import { cn } from '@/lib/utils'
import { Tooltip, TooltipContent, TooltipProvider, TooltipTrigger } from '@/components/ui/tooltip'
import { Sparkles } from 'lucide-react'

export type AgentKind = 'test_generation' | 'healing' | 'impact_analysis' | 'defect_triage' | 'classification'

interface AgentTaskIndicatorProps {
  agentKind: AgentKind
  confidence: number
  className?: string
}

const agentLabels: Record<AgentKind, string> = {
  test_generation: 'Test Generation',
  healing: 'Self-Healing',
  impact_analysis: 'Impact Analysis',
  defect_triage: 'Defect Triage',
  classification: 'Classification',
}

export function AgentTaskIndicator({ agentKind, confidence, className }: AgentTaskIndicatorProps) {
  return (
    <TooltipProvider>
      <Tooltip delayDuration={200}>
        <TooltipTrigger asChild>
          <span
            className={cn(
              'inline-flex items-center gap-1 px-2 py-0.5 rounded-full',
              'bg-gradient-to-r from-indigo-50 to-violet-50',
              'border border-indigo-200/50',
              'text-xs font-medium text-indigo-700',
              'cursor-default',
              className
            )}
          >
            <Sparkles className="h-3 w-3 text-indigo-500" />
            <span>AI Agent</span>
          </span>
        </TooltipTrigger>
        <TooltipContent side="top" className="max-w-xs">
          <div className="space-y-1.5">
            <div className="flex items-center gap-2">
              <Sparkles className="h-4 w-4 text-indigo-500" />
              <span className="font-medium">Generated by Voltus AI Agent</span>
            </div>
            <div className="flex items-center justify-between text-sm">
              <span className="text-muted-foreground">Task Type:</span>
              <span>{agentLabels[agentKind]}</span>
            </div>
            <div className="flex items-center justify-between text-sm">
              <span className="text-muted-foreground">Confidence:</span>
              <span className={cn(
                'font-mono',
                confidence >= 90 && 'text-emerald-600',
                confidence >= 70 && confidence < 90 && 'text-amber-600',
                confidence < 70 && 'text-red-600'
              )}>
                {confidence}%
              </span>
            </div>
          </div>
        </TooltipContent>
      </Tooltip>
    </TooltipProvider>
  )
}
